# these secrets should be injected by Vault HashiCorp or similar secret management tool
# templates/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # These values are base64 encoded
  # To encode: echo -n "password" | base64
  mysql-root-password: cGFzc3dvcmQ=  # "password" in base64
  mysql-password: cGFzc3dvcmQ=       # "password" in base64