# templates/mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  selector:
    app: mysql  # This connects to Pods labeled with app: mysql
  ports:
    - port: 3306      # The port other Pods use to connect to this service
      targetPort: 3306 # The port MySQL is listening on inside its Pod
      protocol: TCP
      name: mysql-port
  type: ClusterIP    # Only accessible from within the cluster